export default {
  SOCKET_CONNECT: 'SOCKET_CONNECT',
  SOCKET_SET: 'SOCKET_SET',
    
  SET_PLAYER: 'SET_PLAYER',

  GAME_CONNECTED: 'GAME_CONNECTED',
  GAME_UPDATE: 'GAME_UPDATE',
  GAME_UPDATE_STATE: 'GAME_UPDATE_STATE',
  GAME_PLAY_TURN: 'GAME_PLAY_TURN',
  NEW_GAME_CREATED: 'NEW_GAME_CREATED',

  RESET: 'RESET',
  APP_ERROR: 'APP_ERROR',
  APP_CLEAR_ERROR: 'APP_CLEAR_ERROR',

  CHAT_INPUT: 'CHAT_INPUT',
  CHAT_ADD_MESSAGE: 'CHAT_ADD_MESSAGE',
  CHAT_SEND_MESSAGE: 'CHAT_SEND_MESSAGE',
  CHAT_SET_STATE: 'CHAT_SET_STATE',
};