module.exports = {
  GAME_START: 'GAME_START', 
  GAME_CONNECT: 'GAME_CONNECT',

  GAME_CONNECTED: 'GAME_CONNECTED',
  GAME_NOT_FOUND: 'GAME_NOT_FOUND',

  GAME_CREATE: 'GAME_CREATE',
  GAME_CREATED: 'GAME_CREATED',

  GAME_DELETED: 'GAME_DELETED',
  GAME_UPDATE: 'GAME_UPDATE',

  GAME_RESTART: 'GAME_RESTART',

  CHAT_STATE: 'CHAT_STATE',
  CHAT_NEW_MESSAGE: 'CHAT_NEW_MESSAGE',
  CHAT_UPDATE: 'CHAT_UPDATE',

  PLAY_TURN: 'PLAY_TURN',

  ERROR: 'ERROR',
};
